Weather APP Using API
AndresFMoya/JS-weather_app pull request #2
Opened 2019-12-29 14:14 UTC by AndresFMoya

Good day TSEs.

Requirements of weather app were met. Looking to hear your comments.

Best!

2020-01-02 02:27 UTC, bellom requested changes
## Hi @AndresFMoya  :clap: 
#### Awesome job so far!! :+1: 
#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1:, just few issues left to work on............ :slightly_smiling_face: 

Below are part of the checklist for this project, kindly work on these few things listed below;

1. Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2. You are using `drop down` checkout the screenshot from your web page below;
![image](https://user-images.githubusercontent.com/31897434/71649541-0b44b400-2d10-11ea-920a-c04b9f60f0c2.png)


You should use a toggle control to determine if the result will be shown in Celsius or Fahrenheit ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-02 02:27 UTC, bellom commented on src/framework.js
> +   * Select the route handler and call App#render.
**Kindly remove commented code, you can always use git history to access previous code right :slightly_smiling_face: **

2020-01-03 15:37 UTC, AndresFMoya commented
Hi @bellom. Thanks for your feedback! The comments were deleted and a toggle control was added to switch between units.

Looking to hear your comments.

Best!

2020-01-07 00:55 UTC, bellom approved these changes
## Hi @AndresFMoya  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-07 01:19 UTC, merged